"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(64, 25);
var myPoint2 = new point_1.Point(36, 49);
var myPoint3 = new point_1.Point(-25, 49);
var myPoint4 = new point_1.Point(-250, 87);
var myPoint5 = new point_1.Point(33.32, 4900);
var myPoint6 = new point_1.Point(-1, +1);
var myPoint7 = new point_1.Point(50, 50);
var myPoint8 = new point_1.Point(49050, 49050);
console.log(myPoint.toString());
console.log(myPoint.distanceToOrigin());
console.log(myPoint.calculateDistance(myPoint2));
console.log(myPoint.calculateQuadrant());
console.log(myPoint3.calculateQuadrant());
console.log(myPoint.calculateDistance(myPoint));
console.log(myPoint.calculateDistance(myPoint2));
console.log(myPoint.calculateDistance(myPoint3));
console.log(myPoint.calculateDistance(myPoint4));
console.log(myPoint.calculateDistance(myPoint5));
console.log(myPoint.calculateDistance(myPoint6));
console.log(myPoint.calculateDistance(myPoint7));
console.log(myPoint.calculateDistance(myPoint8));
